# Generated by Django 2.1.7 on 2019-03-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190328_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='create_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='create_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='create_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='create_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='update_time',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
