# Generated by Django 2.1.7 on 2019-03-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
